import json, os

deities = [
    (0, "Julianos", "Justice, logic, history, scholarship, contradiction",
     "Master the skills of the Mage. Strive to raise your Magicka. Never openly break the laws of Skyrim.",
     "Follower: Spells cost less to cast. Devotee: Spells and scrolls are more effective."),
    (1, "Syrabane", "Magic, arcane lore, protection of knowledge",
     "Read books that teach new skills. Study a wide variety of spells. High Elves are most deserving of favor.",
     "Follower: More likely to find spell tomes and scrolls on killed enemies. Devotee: Learn all Mage skills faster."),
    (2, "Magnus", "Magic, the sun, arcane knowledge",
     "Practice magic successfully while praying. Safeguard the Eye of Magnus. Create enchanted items.",
     "Follower: Magicka does not regenerate, but praying rapidly replenishes it and spells cost less. Devotee: Praying auto-casts beneficial self-targeted spells for free."),
    (3, "Jephre", "The Green, nature, the songs of nature, the Spinners",
     "Explore new locations. Read the stories of others. Hunt animals. Wood Elves are most deserving of favor.",
     "Follower: Movement speed increased out of combat. Devotee: Stamina regenerates very quickly out of combat, praying brings clear weather."),
    (4, "Mara", "Love, compassion, marriage, fertility",
     "Be married. Own one or more houses. Be generous to beggars and children. Receive the blessing of Lover's Comfort. Never openly break the laws of Skyrim.",
     "Follower: Pray to cure all diseases affecting you or allies. Devotee: Living allies within 40 feet are healed per second."),
    (5, "Meridia", "Light, beauty, energy, initiative, the undead (enemy)",
     "Slay the undead. Never summon the undead or become one. High Elves and those skilled in Restoration are most deserving of favor.",
     "Follower: Attacks and spells are more effective against undead. Devotee: Activate an undead opponent to call down a solar strike."),
    (6, "Azura", "Dusk and dawn, magic, vanity, the transition between night and day",
     "Trap souls. Explore new locations. Pray only at twilight, preferably outside. Dark Elves and those skilled in Illusion are most deserving of favor.",
     "Follower: Nearby foes suffer reduced magic resistance. Devotee: Paralyze a weakened opponent in combat."),
    (7, "Talos", "War, governance, the empires of Men",
     "Bring the Civil War to a conclusion. Learn the dragon tongue. Absorb dragon souls. Slay elves and the Thalmor. Never openly break the laws of Skyrim.",
     "Follower: Attacks and shouts are more effective against elves. Devotee: Shout cooldown halved when enemies die nearby."),
    (8, "Akatosh", "Time, endurance, invincibility, everlasting legitimacy",
     "Fulfill your destiny by saving Tamriel. Raise your character level. Absorb dragon souls. Never openly break the laws of Skyrim.",
     "Follower: Attacks, spells and shouts are more effective against dragons. Devotee: Praying resets the cooldown of your most recently used shout and power."),
    (9, "Dibella", "Beauty, love, arts, music, aesthetics",
     "Persuade others. Receive the blessing of Lover's Comfort. Find a new Sybil for the Temple of Dibella. Pray only in the nude. Never openly break the laws of Skyrim.",
     "Follower: Lover's Comfort also improves all skills. Devotee: Activate a person in combat to make them unequip items and follow you."),
    (10, "Phynaster", "The protection of the Summerset Isles, endurance, patience",
     "Explore new locations. Find the standing stones of Skyrim. Harvest the fruits of nature. Bretons are most deserving of favor.",
     "Follower: Health, Magicka and Stamina regenerate faster when standing still. Devotee: Teleport back to the last location where you prayed."),
    (11, "Mehrunes Dagon", "Destruction, change, revolution, energy, ambition",
     "Slay people who stand in your way. Defile the shrines of enemies. Those skilled in Destruction are most deserving of favor.",
     "Follower: Daedric fire drains Magicka while praying; stop at low Magicka for more favor. Devotee: Nearby foes burn and explode on death."),
    (12, "Vaermina", "Dreams, nightmares, evil omens, psychological terror",
     "Witness the death of those under your mind affecting spells. Kill people in their sleep. Sleep to pray. Those skilled in Illusion are most deserving of favor.",
     "Follower: Mind affecting illusion spells work on higher level targets. Devotee: Activate a sleeping person to summon an illusion companion."),
    (13, "Zenithar", "Work, commerce, crafts, communication",
     "Invest in stores and merchants. Seek out skill training. Make weapons and armor. Never openly break the laws of Skyrim.",
     "Follower: Learn Smithing, Alchemy and Enchanting faster and they are more effective. Devotee: Pray to buy and sell items directly."),
    (14, "Boethiah", "Deceit, conspiracy, secret plots, assassination, treason",
     "Murder the innocent. Strike unseen with sneak attacks. Poison your weapons. Dark Elves are most deserving of favor.",
     "Follower: Attacks deal more damage when fighting only one opponent. Devotee: Invoke Daedric Invisibility; breaking it with a sneak attack deals extra damage."),
    (15, "Nocturnal", "Night, darkness, luck, shadows, the unknown",
     "Pickpocket Mysterious Coinpurses. Pick locks. Pray only at night, preferably in darkness. Those skilled in Sneak are most deserving of favor.",
     "Follower: Praying clears non-violent crime bounties. Devotee: Astrally observe the nearest person within 300 feet."),
    (16, "Molag Bal", "Domination, enslavement, the harvesting of souls",
     "Slay people who stand in your way. Trap souls. Live as a vampire and never seek a cure. Those skilled in Destruction are most deserving of favor.",
     "Follower: Absorb Magicka and Stamina from nearby enemies in combat. Devotee: Banish a person in combat to Coldharbour."),
    (17, "Kynareth", "Air, wind, elements, travel, birds",
     "Explore new locations. Strive to raise your Stamina. Receive the Voice of the Sky. Pray only outdoors. Never openly break the laws of Skyrim.",
     "Follower: Movement speed increased in combat. Devotee: Pray to summon a sacred Sabre Cat mount."),
    (18, "Mephala", "Sex, lies, secret murder, obscure plots",
     "Poison your weapons. Strike unseen with sneak attacks. Intimidate the weak. Dark Elves are most deserving of favor.",
     "Follower: Sneak attacks deal more damage from behind. Devotee: Seize control of the nearest person to fight for you."),
    (19, "Arkay", "Life, death, the cycle of souls, burial rites",
     "Slay the undead and their summoners. Perform Arkay's Rites. Never openly break the laws of Skyrim. Never summon the undead or become one.",
     "Follower: Regenerate Health based on missing Health. Devotee: Revive with full Health upon taking fatal damage."),
    (20, "Sanguine", "Hedonism, debauchery, dark reveries",
     "Make mischief and commit crimes worthy of a bounty. Indulge in mead, wine and ale. Find your own way out of jail.",
     "Follower: Health, Magicka and Stamina regenerate faster while a potion or food is active. Devotee: Pray in combat to force nearby hostiles to dance."),
    (21, "Malacath", "The spurned, the ostracised, the betrayed, the bloody oath",
     "Defeat epic foes. Improve weapons and armor. Never commit a crime against the strongholds. Orcs and those skilled in Smithing are most deserving of favor.",
     "Follower: Power attacks deal more damage. Devotee: When enemies die nearby, their killer is healed by overkill damage dealt."),
    (22, "Stendarr", "Mercy, charity, well-earned luck, righteous might",
     "Clear dungeons of evil. Slay daedra and the undead. Complete side quests for the people of Skyrim. Never openly break the laws of Skyrim.",
     "Follower: Take less attack damage from daedra and undead. Devotee: Spend favor to gain improved attack, defense and healing."),
    (23, "Auriel", "Time, the light of the heavens, the Elven aspects of Akatosh",
     "Fulfill your destiny by saving Tamriel. Master all skills. Become Champion at the sacred Chantry. High Elves are most deserving of favor.",
     "Follower: Learn all skills faster. Devotee: Level 100 skills are improved further."),
    (24, "Peryite", "Tasks, pestilence, order among the lowest of Daedra",
     "Catch as many diseases as you can. Accept Gifts of pestilence. Pray only while diseased. Never accept a cure for your afflictions.",
     "Follower: Learn all skills faster. Devotee: Inflict all your diseases on a living opponent plus disease damage per second."),
    (25, "Hircine", "The hunt, sport, the Great Game, the Chase",
     "Slay the living in open combat, especially those stronger. Live as a werewolf. Pray in the wild. Those skilled in Light Armor are most deserving of favor.",
     "Follower: Double attack damage to living targets with low Health. Devotee: Invoke a Hunt to reveal and expose nearby living targets."),
    (26, "Xarxes", "Ancestry, secret knowledge, the scribe of Auri-El",
     "Explore new locations. Read the stories of others. Study a wide variety of spells. Bretons are most deserving of favor.",
     "Follower: Reading a Skill Book while praying grants an extra Skill Point. Devotee: Ascend in a trance, revealing all characters in a large radius."),
    (27, "Shor", "The underworld, the dead, mankind, Sovngarde",
     "Fulfill your destiny by saving Tamriel. Master the skills of the Warrior. Slay elves. Defeat epic foes.",
     "Follower: Take less damage and stagger from elves. Devotee: When entering combat with a mighty foe, a Shield-Thane assists you."),
    (28, "Hermaeus Mora", "Knowledge, memory, the scrying of the tides of Fate",
     "Read Eldritch Pages and bind them into Eldritch Tomes. Read books that teach new skills. Become Champion at the Summit of Apocrypha.",
     "Follower: Find Eldritch Pages on corpses; bind into Tomes that improve magic and shouts. Devotee: Pray to permanently raise a skill."),
    (29, "Clavicus Vile", "Power, wishes, trickery, bargains",
     "Pray to accept a Pact and complete it as written within the allotted time. Never break or ignore Pacts.",
     "Follower: Conjuration spells last longer. Devotee: Pray to make a Wish, permanently gaining an additional perk point."),
    (30, "Namira", "Ancient darkness, revulsion, the foul, cannibalism",
     "Murder the innocent. Poison your weapons. Eat the corpses of the dead with the Ring. Be generous to beggars.",
     "Follower: Reduces Poison Resistance of all nearby. Devotee: Poisoning a person attracts insects, reducing armor and dealing disease damage."),
    (31, "Jyggalag", "Order, logic, deductive reasoning, natural law",
     "Activate Obelisks of Order. Clear dungeons of evil. Slay daedra. Never serve Sheogorath. Those skilled in Heavy Armor are most deserving of favor.",
     "Follower: Obelisks of Order grant Health, Magicka and Stamina. Devotee: Trap an opponent in an inert but invulnerable state."),
    (32, "Trinimac", "Strength, honour, the warrior Aedra",
     "Slay humans. Defeat epic foes. Never accept Boethiah's blessing or serve her. Those skilled in Two-Handed are most deserving of favor.",
     "Follower: Attacks deal more damage to humans. Devotee: Become ethereal and invulnerable until your next attack."),
    (33, "Sheogorath", "Madness, creativity, the mind",
     "Pray often and receive Touch of Madness. Never disrespect cheese.",
     "Follower: Praying grants a random Touch of Madness. Devotee: Receive a Touch of Madness whenever you enter combat."),
    (34, "Sithis", "The Void, change, entropy, the Dark Brotherhood",
     "Murder the innocent. Pray while sacrificing a Human Heart or Flesh. Send victims to the Void. Argonians are most deserving of favor.",
     "Follower: Harder to detect nearby; chance to find Human Hearts on kills. Devotee: Turn a door into a Void portal that pulls in and kills unaware targets."),
    (35, "Z'en", "Toil, payment in kind, the merchant lord",
     "Bribe people as needed. Harvest the fruits of nature. Eat as much food as you want. Those skilled in Speech are most deserving of favor.",
     "Follower: Beneficial potions and food last longer and are better if consumed while praying. Devotee: Pray to open unlimited extradimensional storage."),
    (36, "Satakal", "The world-eating serpent, the beginning and end of all things",
     "Fulfill your destiny by saving Tamriel. Strive to raise your Health. Absorb dragon souls.",
     "Follower: Shrine blessings from other gods are more effective and last longer. Devotee: Pray to become reborn, moving points between attributes."),
    (37, "Tall Papa", "The overseer of all spirits, the highest of the Yokudan gods, endurance",
     "Touch the Fractures scattered around Skyrim. Create enchanted items. Those skilled in Enchanting are most deserving of favor.",
     "Follower: Weapon enchantments drain less charge. Devotee: On death, enter ethereal state; if combat ends in time, revive."),
    (38, "the HoonDing", "Perseverance, the spirit of going forward, movement against all odds",
     "Slay your foes in open combat, especially those stronger. Those skilled in One-Handed are most deserving of favor.",
     "Follower: Staggering an opponent reduces their armor. Devotee: Chance to resist stagger from attacks and bashes."),
    # 39 is unused
    (40, "the Animal Gods", "The old animal god traditions; the Bear, the Crow, the Fox, the Hawk, the Snake, the Wolf",
     "Slay people who stand in your way. Absorb dragon souls. Assume powers through prayer. Nords are most deserving of favor.",
     "Follower: Sacrifice gemstones while praying to assume animal god powers. Devotee: Assume the powers of the Dragon."),
    (41, "Baan Dar", "Thieves, the bandit, clever tricks, the clever merchant",
     "Pick locks and pockets successfully. Khajiit and those skilled in Archery are most deserving of favor.",
     "Follower: Buying from other races costs more, but pickpocketing is easier. Devotee: Put skooma in people's inventory, then pray to ignite them."),
    (42, "Ebonarm", "War, warriors, the Black Knight",
     "Slay daedra. Defeat epic foes. Complete miscellaneous quests. Those skilled in Block are most deserving of favor.",
     "Follower: Attacks are more effective against daedra and their summoners. Devotee: Reduces armor of nearby enemies; you gain the total amount."),
    (43, "Rajhin", "Thieves, rogues, the master thief, luck",
     "Explore new locations. Bribe people. Pick locks. Those skilled in Lockpicking are most deserving of favor.",
     "Follower: Find additional gold in containers. Devotee: Pray to break a lock within 20 feet."),
    (44, "Riddle'Thar", "The cosmic order of the moons, the Two-Moons Dance, Khajiiti faith",
     "Master skills of the Warrior, Thief and Mage equally. Strive to raise Health, Magicka and Stamina. Pray only at night.",
     "Follower: All skills improved. Devotee: An ancient Mane grants a blessing appropriate for upcoming challenges."),
    (45, "Morwha", "Love, fertility, the mother goddess of the Yokudan pantheon",
     "Be married. Receive the blessing of Lover's Comfort. Harvest the fruits of nature. Eat as much food as you want.",
     "Follower: Praying restores Health for you and nearby allies. Devotee: Praying blesses you with enchanted fruit."),
    (46, "Leki", "Sword-craft, the sublime art of the blade, the Saint of the Spirit Sword",
     "Bring the Civil War to a conclusion. Make and improve weapons. Master the skills of the Warrior.",
     "Follower: Power attacks ignore armor. Devotee: Spend favor to gain increased melee damage for 10 minutes."),
    (47, "the Hist", "The ancient trees of Black Marsh, Argonian souls, the Hist-sap",
     "Explore new locations. Slay daedra. Pray only outdoors. Never summon a daedra.",
     "Follower: Pray to gain a bonus to all attributes. Devotee: Absorb Magicka and Stamina of dead creatures and people nearby."),
    (48, "St. Alessia", "The first Empress of Men, freedom, salvation, the Alessian Order",
     "Have a follower at your side. Slay elves. Receive the blessing of a Divine.",
     "Follower: Pray for a Divine blessing of your choice. Devotee: Talk to non-hostile humans to make them a friend and potential follower."),
    (49, "Mannimarco", "Necromancy, undeath, the Worm Cult",
     "Trap souls. Pray only at night. Never accept Arkay's blessing. Those skilled in Conjuration are most deserving of favor.",
     "Follower: Undead conjured at night last longer. Devotee: Allied conjured undead deal more damage and regenerate Health."),
    (50, "the All-Maker", "The Skaal concept of the divine force that created all things",
     "Cleanse the All-Maker Stones. Hunt animals. Explore new locations. Pray only outdoors. Nords are most deserving of favor.",
     "Follower: Healing spells restore more Health. Devotee: After using an All-Maker Stone power, pray to have it restored."),
    (51, "the Magna-Ge", "Stars, the starry heavens, Magnus's kin who fled Mundus",
     "Create enchanted items. Explore new locations. Pray only outdoors at night. High Elves and those skilled in Alteration are most deserving of favor.",
     "Follower: Gain weapon charge per second. Devotee: Let the Magna-Ge carry you to a location within line of sight."),
]

entries = []
for wid, name, domain, tenets, boons in deities:
    t = tenets.rstrip(".")
    b = boons.rstrip(".")
    content = f"{name}'s domain is {domain}. The tenets of {name} worship are: {t}. The boons granted by {name} are: {b}."
    entries.append({
        "content": content,
        "condition_expr": f'get_name(actorUUID) == "{name}"',
        "always_inject": True,
        "importance": 0.9,
        "display_name": f"WSN {name}",
        "knowledge_key": f"wsn_deity_{wid}",
        "tags": ["wintersun", "deity"],
        "type": "KNOWLEDGE",
        "emotion": "",
        "location": "",
    })

pack = {
    "skyrimnet_knowledge_pack": {
        "format_version": 2,
        "name": "Wintersun Deity Lore",
        "description": "Domain, tenets, and boons for all 51 Wintersun deities. Each entry is always-injected into the corresponding deity virtual NPC.",
        "version": "1.0.0",
        "author": "Wintersun SkyrimNet Integration",
        "entries": entries,
        "npc_groups": [],
    }
}

os.makedirs("Knowledge", exist_ok=True)
with open("Knowledge/wintersun_deity_lore.sknpack", "w", encoding="utf-8") as f:
    json.dump(pack, f, indent=2, ensure_ascii=False)

print(f"Created knowledge pack with {len(entries)} entries")
print(f"Total size: {os.path.getsize('Knowledge/wintersun_deity_lore.sknpack'):,} bytes")
